---
driver:
  name: ec2
  region: eu-central-1
provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
 username: ["ec2-user"]

# See https://github.com/test-kitchen/kitchen-ec2

platforms:
  - name: amazon
    driver: 
      region: eu-central-1
      image_id: ami-0cfbf4f6db41068ac
      instance_type: t2.large
      subnet_id: subnet-0983e93a407f2cccf
      tags:
        Name: "Kitchen Test Instance ec2"


suites:
  - name: default


