  AWSTemplateFormatVersion: "2010-09-09"
  Description: "Ec2 node with apache"
  Parameters:
    key:
      Description: ssh key
      Type: String
    Name:
      Description: Ec2 Name
      Type: String
    ip:
      Description: IP for Instance
      Type: String
  Mappings:
    AmazonLinuxAMI:
      eu-west-1:
        AMI: ami-08935252a36e25f85
      eu-central-1:
        AMI: ami-0cfbf4f6db41068ac
  Resources: 
    MyEC2Instance: 
      Type: AWS::EC2::Instance
      Properties: 
        ImageId: 
          Fn::FindInMap:
          - AmazonLinuxAMI
          - Ref: AWS::Region
          - AMI
        KeyName: 
          Ref: key
        InstanceType: "t2.micro"
        PrivateIpAddress:
          Ref: ip
        SecurityGroupIds:
          - Fn::ImportValue: demo-transit-node-securitygroup
        SubnetId: 
          Fn::ImportValue: demo-transit-subnetA
        Tags:
          -
            Key: Name
            Value: 
              Ref: Name
        UserData:
          Fn::Base64: |
            #!/bin/bash -xe
            yum update -y
            yum install -y httpd24
            service httpd start
            chkconfig httpd on
            echo "Node A" >/var/www/html/index.html
